package rules

import com.karthik.drools1.model.Product;
import java.math.BigDecimal;

rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
	end
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
	end
rule "within checker"
	when 
		// productObject: Product(ltv > new BigDecimal("89.01") && ltv < new BigDecimal("90.01"))
		productObject: Product(ltv > 89.01B && ltv < 90.01B)
			then
		productObject.setWithin(true);
	end
	

